# Minimal rdkit.Chem stub override.
# See stubs/rdkit/__init__.pyi for the reason this exists.
from typing import Optional

class Mol: ...

def MolFromSmiles(smi: str) -> Optional[Mol]: ...
def MolToSmiles(mol: Mol) -> str: ...
